worst_slurs = [
    "nigger",              
    "nigga",
    "reggin",
    "nigg3r",
    "",
    "",
    "",                
    "coon",
    "jigaboo",
    "spic",
    "wetback",
    "beaner",
    "kike",
    "heeb",
    "yid",
    "raghead",
    "sand nigger",
    "towelhead",
    "camel jockey",
    "chink",
    "gook",
    "zipperhead",
    "slant",
    "faggot",
    "fag",
    "tranny",              
    "neger",
    "trannies",
    "shemale",
    "dyke",
    "carpet muncher",
    " cocksucker",
    "cunt"                  
    "twat",
    "paki",
    "wog",
    "abo",
    "coon",
    "darky",
    "darkie",
    "porch monkey",
    "moon cricket",
    "shine",
    "tar baby",
    "cracker"              
    "honky",
    "redskin",
    "injuns",
    "prairie nigger",
    "curry muncher",
    "dothead",
    "hajji",
    "terrorist"    
]       